# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserManager.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11UserManager.proto\"-\n\x0e\x41\x64\x64UserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"C\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1f\n\tDeleteAck\x12\x12\n\ndelete_ack\x18\x01 \x01(\t\"\x0e\n\x0c\x45mptyRequest2\xa4\x01\n\x0bUserManager\x12!\n\x07\x41\x64\x64User\x12\x0f.AddUserRequest\x1a\x05.User\x12!\n\x07GetUser\x12\x0f.GetUserRequest\x1a\x05.User\x12,\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\n.DeleteAck\x12!\n\x07GetList\x12\r.EmptyRequest\x1a\x05.User0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UserManager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDUSERREQUEST']._serialized_start=21
  _globals['_ADDUSERREQUEST']._serialized_end=66
  _globals['_USER']._serialized_start=68
  _globals['_USER']._serialized_end=135
  _globals['_GETUSERREQUEST']._serialized_start=137
  _globals['_GETUSERREQUEST']._serialized_end=165
  _globals['_DELETEUSERREQUEST']._serialized_start=167
  _globals['_DELETEUSERREQUEST']._serialized_end=198
  _globals['_DELETEACK']._serialized_start=200
  _globals['_DELETEACK']._serialized_end=231
  _globals['_EMPTYREQUEST']._serialized_start=233
  _globals['_EMPTYREQUEST']._serialized_end=247
  _globals['_USERMANAGER']._serialized_start=250
  _globals['_USERMANAGER']._serialized_end=414
# @@protoc_insertion_point(module_scope)
